//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.BusinessLogin.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportsmen
    {
        public Sportsmen()
        {
            this.SportsmenInCategories = new HashSet<SportsmenInCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Club { get; set; }
    
        public virtual ICollection<SportsmenInCategory> SportsmenInCategories { get; set; }
    }
}
